# Build the webhook-whereabouts-numanetwork binary
FROM golang:1.25 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o webhook-whereabouts-numanetwork cmd/webhook-whereabouts-numanetwork/main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/webhook-whereabouts-numanetwork .
USER 65532:65532

ENTRYPOINT ["/webhook-whereabouts-numanetwork"]
