nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - kind: MutatingWebhookConfiguration
    path: webhooks/clientConfig/service/name
  - kind: ValidatingWebhookConfiguration
    path: webhooks/clientConfig/service/name

namespace:
- path: webhooks/clientConfig/service/namespace
  kind: MutatingWebhookConfiguration
- path: webhooks/clientConfig/service/namespace
  kind: ValidatingWebhookConfiguration

varReference:
- path: metadata/annotations
  kind: MutatingWebhookConfiguration
- path: metadata/annotations
  kind: ValidatingWebhookConfiguration
