---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - numaflow.numaproj.io
  resources:
  - numanetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - numaflow.numaproj.io
  resources:
  - numanetworks/finalizers
  verbs:
  - update
- apiGroups:
  - numaflow.numaproj.io
  resources:
  - numanetworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - numaflow.numaproj.io
  resources:
  - pipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceclaimtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
