/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:validation:Enum="";Pending;Running;Failed
type NumaNetworkPhase string

const (
	NumaNetworkPhaseUnknown NumaNetworkPhase = ""
	NumaNetworkPhasePending NumaNetworkPhase = "Pending"
	NumaNetworkPhaseRunning NumaNetworkPhase = "Running"
	NumaNetworkPhaseFailed  NumaNetworkPhase = "Failed"
)

// ConnectionType defines how vertices communicate over the NumaNetwork.
// +kubebuilder:validation:Enum=direct;multi-isbsvc
type ConnectionType string

const (
	// ConnectionTypeDirect connects vertices directly via GPU Direct RDMA.
	ConnectionTypeDirect ConnectionType = "direct"
	// ConnectionTypeMultiISBSvc connects vertices through multiple InterStepBufferServices.
	ConnectionTypeMultiISBSvc ConnectionType = "multi-isbsvc"
)

// NumaNetworkSpec defines the desired state of NumaNetwork
type NumaNetworkSpec struct {
	// deviceClassName is the name of the DRA DeviceClass that provides
	// the network devices used for GPU Direct communication.
	// +kubebuilder:validation:MinLength=1
	// +required
	DeviceClassName string `json:"deviceClassName"`

	// connectionType selects how vertices communicate over this network.
	// +kubebuilder:default=direct
	// +optional
	ConnectionType ConnectionType `json:"connectionType,omitempty"`
}

// NumaNetworkStatus defines the observed state of NumaNetwork.
type NumaNetworkStatus struct {
	// phase is the current lifecycle phase of the NumaNetwork.
	// +optional
	Phase NumaNetworkPhase `json:"phase,omitempty"`

	// resourceClaimTemplateName is the name of the ResourceClaimTemplate
	// generated by the controller for this network.
	// +optional
	ResourceClaimTemplateName string `json:"resourceClaimTemplateName,omitempty"`

	// conditions represent the current state of the NumaNetwork resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Standard condition types include:
	// - "Available": the resource is fully functional
	// - "Progressing": the resource is being created or updated
	// - "Degraded": the resource failed to reach or maintain its desired state
	//
	// The status of each condition is one of True, False, or Unknown.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=nn
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// NumaNetwork is the Schema for the numanetworks API
type NumaNetwork struct {
	metav1.TypeMeta `json:",inline"`

	// metadata is a standard object metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// spec defines the desired state of NumaNetwork
	// +required
	Spec NumaNetworkSpec `json:"spec"`

	// status defines the observed state of NumaNetwork
	// +optional
	Status NumaNetworkStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

// NumaNetworkList contains a list of NumaNetwork
type NumaNetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []NumaNetwork `json:"items"`
}

func init() {
	SchemeBuilder.Register(&NumaNetwork{}, &NumaNetworkList{})
}
