/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RefDeviceClass configures the DRA DeviceClass used for NIC assignment.
type RefDeviceClass struct {
	// name is the name of the DeviceClass that defines the NIC type assigned to pods.
	// +kubebuilder:validation:MinLength=1
	// +required
	Name string `json:"name"`
}

// RefResourceClaimDranet configures the DRANET parameters embedded in the
// ResourceClaimTemplate that the controller generates for this NumaNetwork.
// IP assignment is delegated to the dranet webhook via a named profile (ADR-0004).
// ethernetSpeed removed (DRANET does not publish link speed, ADR-0002).
// vlanTag removed (conflicts with BYODP model, ADR-0003).
type RefResourceClaimDranet struct {
	// ipRange is the CIDR block passed to the dranet webhook profile for IPAM.
	// The controller does NOT embed this directly in the RCT opaque config;
	// it is resolved by the webhook provider at admission time (ADR-0004).
	// Example: "192.168.140.0/24"
	// +kubebuilder:validation:Pattern=`^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/([0-9]|[1-2][0-9]|3[0-2])$`
	// +required
	IPRange string `json:"ipRange"`
}

// NumaNetworkSpec defines the desired state of NumaNetwork.
type NumaNetworkSpec struct {
	// refDeviceClass configures the DRA DeviceClass that provides the NIC type.
	// +required
	RefDeviceClass RefDeviceClass `json:"refDeviceClass"`

	// refResourceClaimDranet configures the DRANET parameters embedded in the
	// ResourceClaimTemplate generated by the controller.
	// +required
	RefResourceClaimDranet RefResourceClaimDranet `json:"refResourceClaimDranet"`
}

// NumaNetworkStatus defines the observed state of NumaNetwork.
type NumaNetworkStatus struct {
	// resourceClaimTemplateName is the name of the ResourceClaimTemplate
	// generated by the controller for this NumaNetwork.
	// Convention: <numaNetwork.metadata.name>-rct
	// +optional
	ResourceClaimTemplateName string `json:"resourceClaimTemplateName,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=nn
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// NumaNetwork is the Schema for the numanetworks API
type NumaNetwork struct {
	metav1.TypeMeta `json:",inline"`

	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// spec defines the desired state of NumaNetwork.
	// +required
	Spec NumaNetworkSpec `json:"spec"`

	// status defines the observed state of NumaNetwork.
	// +optional
	Status NumaNetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NumaNetworkList contains a list of NumaNetwork
type NumaNetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NumaNetwork `json:"items"`
}
